name: setup-plastic-scm
description: 'A GitHub action to setup and install Plastic SCM (Unity VCS)'
branding:
  icon: 'database'
  color: 'red'
inputs:
  version:
    description: 'The version of Plastic SCM to install'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
