name: validate
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  validate:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: ./ # buildalon/setup-plastic-scm@v1
        with:
          unity-username: ${{ secrets.UNITY_USERNAME }}
          uvcs-organization: ${{ secrets.UVCS_ORGANIZATION }}
          unity-cloud-project-id: ${{ secrets.UNITY_CLOUD_PROJECT_ID }}
          unity-service-account-credentials: ${{ secrets.UNITY_SERVICE_ACCOUNT_CREDENTIALS }}
      - run: |
          cm version
          cm repository list
